name: N3rdyKits
version: 1.0
description: Plugin de KitPvP
author: N3rdyDev
main: com.n3rdydev.main
commands:
  kit:
    description: Selecionar um kit.
    permission-message: §cNão Possui permissão
    usage: /kit nome-do-kit
