name: N3rdyKits
version: 1.0
description: Plugin de KitPvP
author: N3rdyDev
main: com.n3rdydev.main
commands:
  kit:
    description: Selecionar um kit.
    permission-message: §cNão possui permissão.
    usage: /kit nome-do-kit
  build:
    description: modo construcao
    permission-message: §cNão possui permissão.
    usage: /build
  setarspawn:
    description: definir um spawn.
    permission-message: §cNão possui permissão.
    usage: /setarspawn
  kits:
    description: abre menu de kits.
    permission-message: §cNão possui permissão.
    usage: /kits
  n3rdykits:
    description: plugin comandos.
    permission-message: §cNão possui permissão.
    usage: /n3rdykits <função>
  admin:
    description: invisibilidade para outros jogadores.
    permission-message: §cNão possui permissão.
    usage: /admin
  definir:
    description: define as cordenadas para ser teleportado
    permission-message: §cNão possui permissão.
    usage: /definir [protecao/spawn/arena/warp] values
  gm:
    description: troca de gamemode.
    permission-message: §cNão possui permissão.
    usage: /gm [0/1]
  ping:
    description: retorna o ping do jogador.
    permission-message: §cNão possui permissão.
    usage: /ping